### ISSUE TITLE
Feature: Index job name when it exists in workflow

### ISSUE THREAD

**Issue by Jaryt** [CircleCI-Public/visual-config-editor#32]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

When two workflow jobs exist with the same job definition, they will produce unexpected results:

```yaml
workflows:
  build-and-test:
    jobs:
      - New Job:
          requires:
            &a1
            - New Job
      - New Job:
          requires: *a1
```

In this example, since a job was set to require new job, it ended up updating it for all jobs with the name "New Job". This is very incorrect.

### Describe the solution you'd like

When a job is added to a workflow, where a workflow job with the same name already exists, the user should be prompted with an option to add a name parameter, or index the name of the job.

### Teachability, documentation, adoption, migration strategy

The UI context should be documented.

### What is the motivation / use case for changing the behavior?

Allow the use of the same job multiple times in one workflow.
